// <auto-generated />
using System;
using CardTradeHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardTradeHub.Migrations
{
    [DbContext(typeof(CardTradeHubContext))]
    [Migration("20250422001538_UpdateCardData2")]
    partial class UpdateCardData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardID");

                    b.HasIndex("UserID");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardID = 1,
                            Category = "Pokemon",
                            Condition = "Mint",
                            Description = "2019 Pikachu Pokemon Center Kyoto",
                            ImageUrl = "/images/cards/pikachu.jpg",
                            ListedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 200.00m,
                            Status = "Available",
                            Title = "Pikachu Pokemon Center Kyoto",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 2,
                            Category = "Basketball",
                            Condition = "Good",
                            Description = "Kobe Bryant 2012-13 Limited Auto",
                            ImageUrl = "/images/cards/kobe1.jpg",
                            ListedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 3000.00m,
                            Status = "Available",
                            Title = "Kobe Bryant 2012-13 Limited Auto",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 3,
                            Category = "Football",
                            Condition = "Excellent",
                            Description = "2014 Prizm World Cup Lionel Messi Auto PSA 10",
                            ImageUrl = "/images/cards/messi.jpg",
                            ListedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5000.00m,
                            Status = "Available",
                            Title = "2014 Prizm World Cup Lionel Messi Auto PSA 10",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 4,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "Yao Ming 2016-17 Panini Flawless Autograph",
                            ImageUrl = "/images/cards/yao.jpg",
                            ListedDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1000.00m,
                            Status = "Available",
                            Title = "Yao Ming 2016-17 Panini Flawless Autograph",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 5,
                            Category = "Magic: The Gathering",
                            Condition = "Good",
                            Description = "1993 Unlimited Black Lotus R",
                            ImageUrl = "/images/cards/blacklotus.jpg",
                            ListedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 3000.00m,
                            Status = "Available",
                            Title = "Black Lotus R",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 6,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "National Treasures Kevin Durant Auto USA",
                            ImageUrl = "/images/cards/durant.jpg",
                            ListedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1500.00m,
                            Status = "Available",
                            Title = "National Treasures Kevin Durant Auto USA",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 7,
                            Category = "Baseball",
                            Condition = "Good",
                            Description = "2019 Topps Chrome Shohei Ohtani",
                            ImageUrl = "/images/cards/shohei.jpg",
                            ListedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 50.00m,
                            Status = "Available",
                            Title = "Shohei Ohtani Topps Chrome",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 8,
                            Category = "Football",
                            Condition = "Excellent",
                            Description = "2022-23 Panini Eminence David Beckham Autograph",
                            ImageUrl = "/images/cards/beckham.jpg",
                            ListedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1000.00m,
                            Status = "Available",
                            Title = "David Beckham Autograph Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 9,
                            Category = "Yu-Gi-Oh",
                            Condition = "Near Mint",
                            Description = "Red Eyes Black Dragon PSA 10",
                            ImageUrl = "/images/cards/bluedragon.jpg",
                            ListedDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 8000.00m,
                            Status = "Available",
                            Title = "Red Eyes Black Dragon",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 10,
                            Category = "Basketball",
                            Condition = "Mint",
                            Description = "Kobe Bryant Gold Standard Superscribe Autograph",
                            ImageUrl = "/images/cards/kobe2.jpg",
                            ListedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1500.00m,
                            Status = "Available",
                            Title = "Kobe Bryant Gold Standard Superscribe",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 11,
                            Category = "Pokemon",
                            Condition = "Mint",
                            Description = "Shining Mewtwo GX Rainbow Rare card",
                            ImageUrl = "/images/cards/mewtwo-gx.jpg",
                            ListedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 300.00m,
                            Status = "Available",
                            Title = "Mewtwo GX Rainbow Rare",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 12,
                            Category = "Baseball",
                            Condition = "Good",
                            Description = "2021 Topps Definitive Juan Soto Autograph Card",
                            ImageUrl = "/images/cards/soto.jpg",
                            ListedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2000.00m,
                            Status = "Available",
                            Title = "Juan Soto Autograph Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 13,
                            Category = "Magic: The Gathering",
                            Condition = "Excellent",
                            Description = "Beta Edition Mox Sapphire",
                            ImageUrl = "/images/cards/mox-sapphire.jpg",
                            ListedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 4000.00m,
                            Status = "Available",
                            Title = "Mox Sapphire",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 14,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "2020-21 Kobe Bryant Hoops Slam",
                            ImageUrl = "/images/cards/kobe3.jpg",
                            ListedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 500.00m,
                            Status = "Available",
                            Title = "Kobe Bryant Hoops Slam",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 15,
                            Category = "Yu-Gi-Oh",
                            Condition = "Mint",
                            Description = "First Edition Dark Magician Girl",
                            ImageUrl = "/images/cards/dark-magician-girl.jpg",
                            ListedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 400.00m,
                            Status = "Available",
                            Title = "Dark Magician Girl",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 16,
                            Category = "Hockey",
                            Condition = "Good",
                            Description = "1979 O-Pee-Chee Wayne Gretzky Rookie Card",
                            ImageUrl = "/images/cards/gretzky-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 9000.00m,
                            Status = "Available",
                            Title = "Wayne Gretzky Rookie",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 17,
                            Category = "Pokemon",
                            Condition = "Mint",
                            Description = "Pokemon Lillie Full Art PSA 10",
                            ImageUrl = "/images/cards/lillie.jpg",
                            ListedDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 200.00m,
                            Status = "Available",
                            Title = "Lillie Full Art PSA 10",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 18,
                            Category = "Basketball",
                            Condition = "Excellent",
                            Description = "Kareem Abdul-Jabbar Unparalleled Autograph",
                            ImageUrl = "/images/cards/jabbar.jpg",
                            ListedDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 3500.00m,
                            Status = "Available",
                            Title = "Kareem Abdul-Jabbar Unparalleled Autograph",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 19,
                            Category = "Baseball",
                            Condition = "Good",
                            Description = "Topps Chrome Juan Soto Rookie Card PSA 10",
                            ImageUrl = "/images/cards/soto2.jpg",
                            ListedDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 400.00m,
                            Status = "Available",
                            Title = "Juan Soto Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 20,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "Stephen Curry 2018-19 Immaculate Moments",
                            ImageUrl = "/images/cards/curry.jpg",
                            ListedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2600.00m,
                            Status = "Available",
                            Title = "Stephen Curry 2018-19 Immaculate Moments",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("CardTradeHub.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuyerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisputeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDispute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("CardID");

                    b.HasIndex("SellerID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CardTradeHub.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Customer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cardtradehub.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            LastLoginDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "AQAAAAEAACcQAAAAEHYxOE9wZQ==",
                            RegisterDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.HasOne("CardTradeHub.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardTradeHub.Models.Transaction", b =>
                {
                    b.HasOne("CardTradeHub.Models.User", "Buyer")
                        .WithMany("Transactions")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardTradeHub.Models.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardTradeHub.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Card");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CardTradeHub.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
