// <auto-generated />
using System;
using CardTradeHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardTradeHub.Migrations
{
    [DbContext(typeof(CardTradeHubContext))]
    partial class CardTradeHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardID");

                    b.HasIndex("UserID");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardID = 1,
                            Category = "Pokemon",
                            Condition = "Mint",
                            Description = "First edition Charizard in mint condition",
                            ImageUrl = "/images/cards/charizard.jpg",
                            ListedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1000.00m,
                            Status = "Available",
                            Title = "Charizard First Edition",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 2,
                            Category = "Magic: The Gathering",
                            Condition = "Good",
                            Description = "Rare Black Lotus card from Magic: The Gathering",
                            ImageUrl = "/images/cards/black-lotus.jpg",
                            ListedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5000.00m,
                            Status = "Available",
                            Title = "Black Lotus MTG",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 3,
                            Category = "Yu-Gi-Oh",
                            Condition = "Excellent",
                            Description = "Classic Yu-Gi-Oh! card in excellent condition",
                            ImageUrl = "/images/cards/blue-eyes.jpg",
                            ListedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 500.00m,
                            Status = "Available",
                            Title = "Blue-Eyes White Dragon",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 4,
                            Category = "Pokemon",
                            Condition = "Near Mint",
                            Description = "Extremely rare Pikachu Illustrator promo card",
                            ImageUrl = "/images/cards/pikachu-illustrator.jpg",
                            ListedDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 10000.00m,
                            Status = "Available",
                            Title = "Pikachu Illustrator",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 5,
                            Category = "Magic: The Gathering",
                            Condition = "Good",
                            Description = "Vintage Time Walk card from MTG Alpha set",
                            ImageUrl = "/images/cards/time-walk.jpg",
                            ListedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 3000.00m,
                            Status = "Available",
                            Title = "Time Walk",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 6,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "1986 Fleer Michael Jordan Rookie Card",
                            ImageUrl = "/images/cards/jordan-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 7500.00m,
                            Status = "Available",
                            Title = "Michael Jordan Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 7,
                            Category = "Baseball",
                            Condition = "Good",
                            Description = "1952 Topps Mickey Mantle #311",
                            ImageUrl = "/images/cards/mantle-1952.jpg",
                            ListedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 15000.00m,
                            Status = "Available",
                            Title = "Mickey Mantle 1952 Topps",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 8,
                            Category = "Football",
                            Condition = "Excellent",
                            Description = "2000 Playoff Contenders Tom Brady Rookie Card",
                            ImageUrl = "/images/cards/brady-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 8000.00m,
                            Status = "Available",
                            Title = "Tom Brady Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 9,
                            Category = "Yu-Gi-Oh",
                            Condition = "Near Mint",
                            Description = "Complete set of all 5 Exodia pieces",
                            ImageUrl = "/images/cards/exodia.jpg",
                            ListedDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 800.00m,
                            Status = "Available",
                            Title = "Exodia the Forbidden One",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 10,
                            Category = "Basketball",
                            Condition = "Mint",
                            Description = "2003-04 Upper Deck LeBron James Rookie Card",
                            ImageUrl = "/images/cards/lebron-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 6000.00m,
                            Status = "Available",
                            Title = "LeBron James Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 11,
                            Category = "Pokemon",
                            Condition = "Mint",
                            Description = "Shining Mewtwo GX Rainbow Rare card",
                            ImageUrl = "/images/cards/mewtwo-gx.jpg",
                            ListedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 300.00m,
                            Status = "Available",
                            Title = "Mewtwo GX Rainbow Rare",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 12,
                            Category = "Baseball",
                            Condition = "Good",
                            Description = "1933 Goudey Babe Ruth Baseball Card",
                            ImageUrl = "/images/cards/ruth-1933.jpg",
                            ListedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 12000.00m,
                            Status = "Available",
                            Title = "Babe Ruth 1933 Goudey",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 13,
                            Category = "Magic: The Gathering",
                            Condition = "Excellent",
                            Description = "Beta Edition Mox Sapphire",
                            ImageUrl = "/images/cards/mox-sapphire.jpg",
                            ListedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 4000.00m,
                            Status = "Available",
                            Title = "Mox Sapphire",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 14,
                            Category = "Basketball",
                            Condition = "Near Mint",
                            Description = "1996-97 Topps Chrome Kobe Bryant Rookie Card",
                            ImageUrl = "/images/cards/kobe-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5500.00m,
                            Status = "Available",
                            Title = "Kobe Bryant Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 15,
                            Category = "Yu-Gi-Oh",
                            Condition = "Mint",
                            Description = "First Edition Dark Magician Girl",
                            ImageUrl = "/images/cards/dark-magician-girl.jpg",
                            ListedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 400.00m,
                            Status = "Available",
                            Title = "Dark Magician Girl",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 16,
                            Category = "Hockey",
                            Condition = "Good",
                            Description = "1979 O-Pee-Chee Wayne Gretzky Rookie Card",
                            ImageUrl = "/images/cards/gretzky-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 9000.00m,
                            Status = "Available",
                            Title = "Wayne Gretzky Rookie",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 17,
                            Category = "Pokemon",
                            Condition = "Near Mint",
                            Description = "Pokemon Movie Ancient Mew Promo Card",
                            ImageUrl = "/images/cards/ancient-mew.jpg",
                            ListedDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 200.00m,
                            Status = "Available",
                            Title = "Ancient Mew Promo",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 18,
                            Category = "Football",
                            Condition = "Excellent",
                            Description = "1986 Topps Jerry Rice Rookie Card",
                            ImageUrl = "/images/cards/rice-rookie.jpg",
                            ListedDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 3500.00m,
                            Status = "Available",
                            Title = "Jerry Rice Rookie Card",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 19,
                            Category = "Magic: The Gathering",
                            Condition = "Good",
                            Description = "Alpha Edition Ancestral Recall",
                            ImageUrl = "/images/cards/ancestral-recall.jpg",
                            ListedDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 4500.00m,
                            Status = "Available",
                            Title = "Ancestral Recall",
                            UserID = 1
                        },
                        new
                        {
                            CardID = 20,
                            Category = "Yu-Gi-Oh",
                            Condition = "Near Mint",
                            Description = "First Edition Red Eyes Black Dragon",
                            ImageUrl = "/images/cards/red-eyes.jpg",
                            ListedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 600.00m,
                            Status = "Available",
                            Title = "Red Eyes Black Dragon",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("CardTradeHub.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuyerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisputeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDispute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("CardID");

                    b.HasIndex("SellerID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CardTradeHub.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Customer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cardtradehub.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            LastLoginDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "AQAAAAEAACcQAAAAEHYxOE9wZQ==",
                            RegisterDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.HasOne("CardTradeHub.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardTradeHub.Models.Transaction", b =>
                {
                    b.HasOne("CardTradeHub.Models.User", "Buyer")
                        .WithMany("Transactions")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardTradeHub.Models.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardTradeHub.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Card");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CardTradeHub.Models.Card", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CardTradeHub.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
